#!/bin/bash

## ########################################################################## ##
CATEGORY_FILE_LIST=(
"categories.C1.expanded.src"
#"categories.C1.expanded-development.src"
)

## ########################################################################## ##
