#!/bin/bash

## ########################################################################## ##
## Several helpful functions:
##  - logging handling
##    - echo handling
##    - cmd handling
##    - pause handling
## ########################################################################## ##
export FUNC_SCRIPT_LOGGING_HANDLING="true"
LOG_TYPE="log"
LOG_FILE=""

## -------------------------------------------------------------------------- ##
## FUNCTIONS:
## -------------------------------------------------------------------------- ##
func_init_log_file(){ # log_path="$1"; name="$2" otherwise use script name
  local log_path name
  log_path="$1"; name="$2"
  [ -n "${log_path}" ] || log_path="."
  [ -d "${log_path}" ] || mkdir -p "${log_path}"
  [ -n "${name}" ] || name=$(basename "$0")
  LOG_FILE="${log_path}/${name}.${LOG_TYPE}"
  echo -n > "${LOG_FILE}"
}

## echo
func_echo(){ # text="$1"
  echo "$1"
  [ -f "${LOG_FILE}" ] && echo "$1" >> "${LOG_FILE}"
}

func_echo_base_topic(){ # text="$1"
  func_border; func_echo "# $1"
}

func_echo_topic(){ # text="$1"
  func_echo ""; func_echo "# $1"
}

## cmd
func_cmd(){ # cmd="$1"
  func_echo ""; func_echo "### cmd: $1"
  eval "$1" >/dev/null 2>&1 || { func_echo "ERROR: $?"; return 1; }
}

## cmd & response
func_cmd_response(){ # cmd="$1"
  local cmd
  cmd="$1"
  func_echo ""; func_echo "### cmd & response: ${cmd}"
  if [ -f "${LOG_FILE}" ]; then
    { eval "${cmd}" || echo "ERROR: $?"; } 2>&1 | tee -a "${LOG_FILE}"
  else
    eval "${cmd}" || { func_echo "ERROR: $?"; return 1; }
  fi
}

## -------------------------------------------------------------------------- ##
func_border(){
  func_echo "
********************************************************************************"
}

## -------------------------------------------------------------------------- ##
func_init_caller(){
  export SCRIPT_CALLED="true"
}

## pause
func_pause(){ # text="$1"
  [ -n "$1" ] && func_echo "$1"
  [ "${SCRIPT_CALLED}" = "true" ] || \
    { echo "Press enter to continue..."; read -r; }
}

## ########################################################################## ##

